FROM ubuntu:22.04 as build

RUN DEBIAN_FRONTEND=noninteractive apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libgmp-dev \
    libbenchmark-dev nasm nlohmann-json3-dev libsecp256k1-dev libomp-dev \
    libpqxx-dev git libssl-dev cmake libgrpc++-dev libprotobuf-dev grpc-proto \
    libsodium-dev protobuf-compiler protobuf-compiler-grpc uuid-dev && \
    rm -fr /var/cache/apt/*

WORKDIR /usr/src/app

COPY ./src ./src
COPY ./test ./test
COPY ./tools ./tools
COPY Makefile .
RUN make -j


FROM ubuntu:22.04 as executor

WORKDIR /app
COPY ./testvectors ./testvectors
COPY ./config ./config
COPY ./src/main_sm/fork_1/scripts/rom.json ./src/main_sm/fork_1/scripts/rom.json
COPY ./src/main_sm/fork_2/scripts/rom.json ./src/main_sm/fork_2/scripts/rom.json
COPY ./src/main_sm/fork_3/scripts/rom.json ./src/main_sm/fork_3/scripts/rom.json
COPY ./src/main_sm/fork_4/scripts/rom.json ./src/main_sm/fork_4/scripts/rom.json
COPY ./src/main_sm/fork_5/scripts/rom.json ./src/main_sm/fork_5/scripts/rom.json
COPY ./src/main_sm/fork_6/scripts/rom.json ./src/main_sm/fork_6/scripts/rom.json

RUN DEBIAN_FRONTEND=noninteractive apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y libgmp-dev \
    nlohmann-json3-dev libsecp256k1-dev libomp-dev libpqxx-dev libssl-dev \
    libgrpc++-dev libprotobuf-dev grpc-proto libsodium-dev && \
    rm -fr /var/cache/apt/*

COPY --from=build /usr/src/app/build/zkProver /usr/local/bin/zkProver

ENTRYPOINT []


FROM executor as prover

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y awscli && \
    rm -fr /var/cache/apt/*
WORKDIR /app/config
RUN aws s3 cp s3://de012a78750e59b808d922b39535e862/v0.6.0.0-rc.1/c12a c12a --recursive --no-sign-request --region=eu-west-1
RUN aws s3 cp s3://de012a78750e59b808d922b39535e862/v0.6.0.0-rc.1/final final --recursive --no-sign-request --region=eu-west-1
RUN aws s3 cp s3://de012a78750e59b808d922b39535e862/v0.6.0.0-rc.1/recursive1 recursive1 --recursive --no-sign-request --region=eu-west-1
RUN aws s3 cp s3://de012a78750e59b808d922b39535e862/v0.6.0.0-rc.1/recursive2 recursive2 --recursive --no-sign-request --region=eu-west-1
RUN aws s3 cp s3://de012a78750e59b808d922b39535e862/v0.6.0.0-rc.1/recursivef recursivef --recursive --no-sign-request --region=eu-west-1
RUN aws s3 cp s3://de012a78750e59b808d922b39535e862/v0.6.0.0-rc.1/scripts scripts --recursive --no-sign-request --region=eu-west-1
RUN aws s3 cp s3://de012a78750e59b808d922b39535e862/v0.6.0.0-rc.1/zkevm/zkevm.const zkevm/ --no-sign-request --region=eu-west-1
RUN aws s3 cp s3://de012a78750e59b808d922b39535e862/v0.6.0.0-rc.1/zkevm/zkevm.consttree zkevm/ --no-sign-request --region=eu-west-1
RUN aws s3 cp s3://de012a78750e59b808d922b39535e862/v0.6.0.0-rc.1/zkevm/zkevm.starkinfo.json zkevm/ --no-sign-request --region=eu-west-1
RUN aws s3 cp s3://de012a78750e59b808d922b39535e862/v0.6.0.0-rc.1/zkevm/zkevm.verifier.dat zkevm/ --no-sign-request --region=eu-west-1
RUN aws s3 cp s3://de012a78750e59b808d922b39535e862/v0.6.0.0-rc.1/zkevm/zkevm.verkey.json zkevm/ --no-sign-request --region=eu-west-1

WORKDIR /app
ENTRYPOINT []
