#include "goldilocks_cubic_extension.hpp"
#include "zhInv.hpp"
#include "starks.hpp"
#include "constant_pols_starks.hpp"
#include "allSteps.hpp"

void AllSteps::step3prev_first(StepsParams &params, uint64_t i) {
     Goldilocks::Element tmp_74;
     Goldilocks::copy(tmp_74, params.pols[12 + i*15]);
     Goldilocks::Element tmp_75;
     Goldilocks::copy(tmp_75, params.pols[13 + ((i + 1)%1024)*15]);
     Goldilocks::Element tmp_76;
     Goldilocks::mul(tmp_76, params.pols[12 + i*15], params.pols[13 + ((i + 1)%1024)*15]);
     Goldilocks::Element tmp_77;
     Goldilocks::copy(tmp_77,  params.pConstPols->getElement(7,i));
     Goldilocks::Element tmp_78;
     Goldilocks::copy(tmp_78,  params.pConstPols->getElement(8,i));
     Goldilocks::Element tmp_79;
     Goldilocks::copy(tmp_79, params.pols[14 + i*15]);
     Goldilocks::Element tmp_80;
     Goldilocks::copy(tmp_80,  params.pConstPols->getElement(6,i));
     Goldilocks3::Element tmp_12;
     Goldilocks3::mul(tmp_12, tmp_77, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_13;
     Goldilocks3::add(tmp_13, tmp_78, tmp_12);
     Goldilocks3::Element tmp_14;
     Goldilocks3::mul(tmp_14, (Goldilocks3::Element &)*params.challenges[0], tmp_13);
     Goldilocks3::Element tmp_15;
     Goldilocks3::add(tmp_15, tmp_79, tmp_14);
     Goldilocks3::Element tmp_16;
     Goldilocks3::sub(tmp_16, tmp_15, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_17;
     Goldilocks3::mul(tmp_17, tmp_80, tmp_16);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[49152 + i*12]), tmp_17, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::Element tmp_81;
     Goldilocks::copy(tmp_81, params.pols[11 + i*15]);
     Goldilocks3::Element tmp_18;
     Goldilocks3::mul(tmp_18, tmp_74, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_19;
     Goldilocks3::add(tmp_19, tmp_75, tmp_18);
     Goldilocks3::Element tmp_20;
     Goldilocks3::mul(tmp_20, tmp_19, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_21;
     Goldilocks3::add(tmp_21, tmp_76, tmp_20);
     Goldilocks3::Element tmp_22;
     Goldilocks3::sub(tmp_22, tmp_21, (Goldilocks3::Element &)(params.pols[49152 + i*12]));
     Goldilocks3::Element tmp_23;
     Goldilocks3::mul(tmp_23, tmp_81, tmp_22);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[21513 + i*21]), tmp_23, (Goldilocks3::Element &)(params.pols[49152 + i*12]));
     Goldilocks::Element tmp_82;
     Goldilocks::copy(tmp_82,  params.pConstPols->getElement(7,(i+1)%1024));
     Goldilocks::Element tmp_83;
     Goldilocks::copy(tmp_83,  params.pConstPols->getElement(8,(i+1)%1024));
     Goldilocks::Element tmp_84;
     Goldilocks::copy(tmp_84, params.pols[14 + ((i + 1)%1024)*15]);
     Goldilocks::Element tmp_85;
     Goldilocks::copy(tmp_85,  params.pConstPols->getElement(6,(i+1)%1024));
     Goldilocks3::Element tmp_24;
     Goldilocks3::mul(tmp_24, tmp_82, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_25;
     Goldilocks3::add(tmp_25, tmp_83, tmp_24);
     Goldilocks3::Element tmp_26;
     Goldilocks3::mul(tmp_26, (Goldilocks3::Element &)*params.challenges[0], tmp_25);
     Goldilocks3::Element tmp_27;
     Goldilocks3::add(tmp_27, tmp_84, tmp_26);
     Goldilocks3::Element tmp_28;
     Goldilocks3::sub(tmp_28, tmp_27, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_29;
     Goldilocks3::mul(tmp_29, tmp_85, tmp_28);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[49152 + ((i + 1)%1024)*12]), tmp_29, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_30;
     Goldilocks3::add(tmp_30, (Goldilocks3::Element &)(params.pols[21513 + i*21]), (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_31;
     Goldilocks3::mul(tmp_31, (Goldilocks3::Element &)(params.pols[49152 + ((i + 1)%1024)*12]), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_32;
     Goldilocks3::add(tmp_32, (Goldilocks3::Element &)(params.pols[49152 + i*12]), tmp_31);
     Goldilocks3::Element tmp_33;
     Goldilocks3::add(tmp_33, Goldilocks::fromU64(1ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_34;
     Goldilocks3::mul(tmp_34, (Goldilocks3::Element &)*params.challenges[2], tmp_33);
     Goldilocks3::Element tmp_35;
     Goldilocks3::add(tmp_35, tmp_32, tmp_34);
     Goldilocks3::Element tmp_36;
     Goldilocks3::mul(tmp_36, tmp_30, tmp_35);
     Goldilocks3::Element tmp_37;
     Goldilocks3::add(tmp_37, Goldilocks::fromU64(1ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[21516 + i*21]), tmp_36, tmp_37);
     Goldilocks3::Element tmp_38;
     Goldilocks3::mul(tmp_38, (Goldilocks3::Element &)(params.pols[15363 + i*6]), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_39;
     Goldilocks3::add(tmp_39, (Goldilocks3::Element &)(params.pols[15360 + i*6]), tmp_38);
     Goldilocks3::Element tmp_40;
     Goldilocks3::add(tmp_40, Goldilocks::fromU64(1ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_41;
     Goldilocks3::mul(tmp_41, (Goldilocks3::Element &)*params.challenges[2], tmp_40);
     Goldilocks3::Element tmp_42;
     Goldilocks3::add(tmp_42, tmp_39, tmp_41);
     Goldilocks3::Element tmp_43;
     Goldilocks3::mul(tmp_43, (Goldilocks3::Element &)(params.pols[15360 + ((i + 1)%1024)*6]), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_44;
     Goldilocks3::add(tmp_44, (Goldilocks3::Element &)(params.pols[15363 + i*6]), tmp_43);
     Goldilocks3::Element tmp_45;
     Goldilocks3::add(tmp_45, Goldilocks::fromU64(1ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_46;
     Goldilocks3::mul(tmp_46, (Goldilocks3::Element &)*params.challenges[2], tmp_45);
     Goldilocks3::Element tmp_47;
     Goldilocks3::add(tmp_47, tmp_44, tmp_46);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[49155 + i*12]), tmp_42, tmp_47);
     Goldilocks::Element tmp_86;
     Goldilocks::copy(tmp_86, params.pols[7 + i*15]);
     Goldilocks::Element tmp_87;
     Goldilocks::copy(tmp_87, params.pols[7 + i*15]);
     Goldilocks::Element tmp_88;
     Goldilocks::copy(tmp_88, params.pols[9 + i*15]);
     Goldilocks3::Element tmp_48;
     Goldilocks3::mul(tmp_48, tmp_86, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_49;
     Goldilocks3::add(tmp_49, tmp_87, tmp_48);
     Goldilocks3::Element tmp_50;
     Goldilocks3::sub(tmp_50, tmp_49, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_51;
     Goldilocks3::mul(tmp_51, tmp_88, tmp_50);
     Goldilocks3::Element tmp_89;
     Goldilocks3::add(tmp_89, tmp_51, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[49158 + i*12]), tmp_89, (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks::Element tmp_90;
     Goldilocks::copy(tmp_90, params.pols[8 + i*15]);
     Goldilocks::Element tmp_91;
     Goldilocks::copy(tmp_91, params.pols[8 + i*15]);
     Goldilocks::Element tmp_92;
     Goldilocks::copy(tmp_92, params.pols[10 + i*15]);
     Goldilocks3::Element tmp_52;
     Goldilocks3::mul(tmp_52, tmp_90, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_53;
     Goldilocks3::add(tmp_53, tmp_91, tmp_52);
     Goldilocks3::Element tmp_54;
     Goldilocks3::sub(tmp_54, tmp_53, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_55;
     Goldilocks3::mul(tmp_55, tmp_92, tmp_54);
     Goldilocks3::Element tmp_93;
     Goldilocks3::add(tmp_93, tmp_55, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[49161 + i*12]), tmp_93, (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks::Element tmp_94;
     Goldilocks::copy(tmp_94, params.pols[2 + i*15]);
     Goldilocks3::Element tmp_56;
     Goldilocks3::mul(tmp_56, (Goldilocks::Element &)*params.x_n[i], (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_57;
     Goldilocks3::add(tmp_57, tmp_94, tmp_56);
     Goldilocks3::Element tmp_95;
     Goldilocks3::add(tmp_95, tmp_57, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks::Element tmp_96;
     Goldilocks::copy(tmp_96, params.pols[3 + i*15]);
     Goldilocks3::Element tmp_58;
     Goldilocks3::mul(tmp_58, Goldilocks::fromU64(12275445934081160404ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_59;
     Goldilocks3::mul(tmp_59, (Goldilocks::Element &)*params.x_n[i], tmp_58);
     Goldilocks3::Element tmp_60;
     Goldilocks3::add(tmp_60, tmp_96, tmp_59);
     Goldilocks3::Element tmp_61;
     Goldilocks3::add(tmp_61, tmp_60, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_97;
     Goldilocks3::mul(tmp_97, tmp_95, tmp_61);
     Goldilocks::Element tmp_98;
     Goldilocks::copy(tmp_98, params.pols[4 + i*15]);
     Goldilocks3::Element tmp_62;
     Goldilocks3::mul(tmp_62, Goldilocks::fromU64(4756475762779100925ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_63;
     Goldilocks3::mul(tmp_63, (Goldilocks::Element &)*params.x_n[i], tmp_62);
     Goldilocks3::Element tmp_64;
     Goldilocks3::add(tmp_64, tmp_98, tmp_63);
     Goldilocks3::Element tmp_65;
     Goldilocks3::add(tmp_65, tmp_64, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[21519 + i*21]), tmp_97, tmp_65);
     Goldilocks::Element tmp_99;
     Goldilocks::copy(tmp_99,  params.pConstPols->getElement(3,i));
     Goldilocks3::Element tmp_66;
     Goldilocks3::mul(tmp_66, tmp_99, (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_67;
     Goldilocks3::add(tmp_67, tmp_94, tmp_66);
     Goldilocks3::Element tmp_100;
     Goldilocks3::add(tmp_100, tmp_67, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks::Element tmp_101;
     Goldilocks::copy(tmp_101,  params.pConstPols->getElement(4,i));
     Goldilocks3::Element tmp_68;
     Goldilocks3::mul(tmp_68, tmp_101, (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_69;
     Goldilocks3::add(tmp_69, tmp_96, tmp_68);
     Goldilocks3::Element tmp_70;
     Goldilocks3::add(tmp_70, tmp_69, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_102;
     Goldilocks3::mul(tmp_102, tmp_100, tmp_70);
     Goldilocks::Element tmp_103;
     Goldilocks::copy(tmp_103,  params.pConstPols->getElement(5,i));
     Goldilocks3::Element tmp_71;
     Goldilocks3::mul(tmp_71, tmp_103, (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_72;
     Goldilocks3::add(tmp_72, tmp_98, tmp_71);
     Goldilocks3::Element tmp_73;
     Goldilocks3::add(tmp_73, tmp_72, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[21522 + i*21]), tmp_102, tmp_73);
}

void AllSteps::step3prev_i(StepsParams &params, uint64_t i) {
     Goldilocks::Element tmp_74;
     Goldilocks::copy(tmp_74, params.pols[12 + i*15]);
     Goldilocks::Element tmp_75;
     Goldilocks::copy(tmp_75, params.pols[13 + ((i + 1)%1024)*15]);
     Goldilocks::Element tmp_76;
     Goldilocks::mul(tmp_76, params.pols[12 + i*15], params.pols[13 + ((i + 1)%1024)*15]);
     Goldilocks::Element tmp_77;
     Goldilocks::copy(tmp_77,  params.pConstPols->getElement(7,i));
     Goldilocks::Element tmp_78;
     Goldilocks::copy(tmp_78,  params.pConstPols->getElement(8,i));
     Goldilocks::Element tmp_79;
     Goldilocks::copy(tmp_79, params.pols[14 + i*15]);
     Goldilocks::Element tmp_80;
     Goldilocks::copy(tmp_80,  params.pConstPols->getElement(6,i));
     Goldilocks3::Element tmp_12;
     Goldilocks3::mul(tmp_12, tmp_77, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_13;
     Goldilocks3::add(tmp_13, tmp_78, tmp_12);
     Goldilocks3::Element tmp_14;
     Goldilocks3::mul(tmp_14, (Goldilocks3::Element &)*params.challenges[0], tmp_13);
     Goldilocks3::Element tmp_15;
     Goldilocks3::add(tmp_15, tmp_79, tmp_14);
     Goldilocks3::Element tmp_16;
     Goldilocks3::sub(tmp_16, tmp_15, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_17;
     Goldilocks3::mul(tmp_17, tmp_80, tmp_16);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[49152 + i*12]), tmp_17, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::Element tmp_81;
     Goldilocks::copy(tmp_81, params.pols[11 + i*15]);
     Goldilocks3::Element tmp_18;
     Goldilocks3::mul(tmp_18, tmp_74, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_19;
     Goldilocks3::add(tmp_19, tmp_75, tmp_18);
     Goldilocks3::Element tmp_20;
     Goldilocks3::mul(tmp_20, tmp_19, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_21;
     Goldilocks3::add(tmp_21, tmp_76, tmp_20);
     Goldilocks3::Element tmp_22;
     Goldilocks3::sub(tmp_22, tmp_21, (Goldilocks3::Element &)(params.pols[49152 + i*12]));
     Goldilocks3::Element tmp_23;
     Goldilocks3::mul(tmp_23, tmp_81, tmp_22);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[21513 + i*21]), tmp_23, (Goldilocks3::Element &)(params.pols[49152 + i*12]));
     Goldilocks::Element tmp_82;
     Goldilocks::copy(tmp_82,  params.pConstPols->getElement(7,(i+1)%1024));
     Goldilocks::Element tmp_83;
     Goldilocks::copy(tmp_83,  params.pConstPols->getElement(8,(i+1)%1024));
     Goldilocks::Element tmp_84;
     Goldilocks::copy(tmp_84, params.pols[14 + ((i + 1)%1024)*15]);
     Goldilocks::Element tmp_85;
     Goldilocks::copy(tmp_85,  params.pConstPols->getElement(6,(i+1)%1024));
     Goldilocks3::Element tmp_24;
     Goldilocks3::mul(tmp_24, tmp_82, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_25;
     Goldilocks3::add(tmp_25, tmp_83, tmp_24);
     Goldilocks3::Element tmp_26;
     Goldilocks3::mul(tmp_26, (Goldilocks3::Element &)*params.challenges[0], tmp_25);
     Goldilocks3::Element tmp_27;
     Goldilocks3::add(tmp_27, tmp_84, tmp_26);
     Goldilocks3::Element tmp_28;
     Goldilocks3::sub(tmp_28, tmp_27, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_29;
     Goldilocks3::mul(tmp_29, tmp_85, tmp_28);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[49152 + ((i + 1)%1024)*12]), tmp_29, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_30;
     Goldilocks3::add(tmp_30, (Goldilocks3::Element &)(params.pols[21513 + i*21]), (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_31;
     Goldilocks3::mul(tmp_31, (Goldilocks3::Element &)(params.pols[49152 + ((i + 1)%1024)*12]), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_32;
     Goldilocks3::add(tmp_32, (Goldilocks3::Element &)(params.pols[49152 + i*12]), tmp_31);
     Goldilocks3::Element tmp_33;
     Goldilocks3::add(tmp_33, Goldilocks::fromU64(1ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_34;
     Goldilocks3::mul(tmp_34, (Goldilocks3::Element &)*params.challenges[2], tmp_33);
     Goldilocks3::Element tmp_35;
     Goldilocks3::add(tmp_35, tmp_32, tmp_34);
     Goldilocks3::Element tmp_36;
     Goldilocks3::mul(tmp_36, tmp_30, tmp_35);
     Goldilocks3::Element tmp_37;
     Goldilocks3::add(tmp_37, Goldilocks::fromU64(1ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[21516 + i*21]), tmp_36, tmp_37);
     Goldilocks3::Element tmp_38;
     Goldilocks3::mul(tmp_38, (Goldilocks3::Element &)(params.pols[15363 + i*6]), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_39;
     Goldilocks3::add(tmp_39, (Goldilocks3::Element &)(params.pols[15360 + i*6]), tmp_38);
     Goldilocks3::Element tmp_40;
     Goldilocks3::add(tmp_40, Goldilocks::fromU64(1ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_41;
     Goldilocks3::mul(tmp_41, (Goldilocks3::Element &)*params.challenges[2], tmp_40);
     Goldilocks3::Element tmp_42;
     Goldilocks3::add(tmp_42, tmp_39, tmp_41);
     Goldilocks3::Element tmp_43;
     Goldilocks3::mul(tmp_43, (Goldilocks3::Element &)(params.pols[15360 + ((i + 1)%1024)*6]), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_44;
     Goldilocks3::add(tmp_44, (Goldilocks3::Element &)(params.pols[15363 + i*6]), tmp_43);
     Goldilocks3::Element tmp_45;
     Goldilocks3::add(tmp_45, Goldilocks::fromU64(1ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_46;
     Goldilocks3::mul(tmp_46, (Goldilocks3::Element &)*params.challenges[2], tmp_45);
     Goldilocks3::Element tmp_47;
     Goldilocks3::add(tmp_47, tmp_44, tmp_46);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[49155 + i*12]), tmp_42, tmp_47);
     Goldilocks::Element tmp_86;
     Goldilocks::copy(tmp_86, params.pols[7 + i*15]);
     Goldilocks::Element tmp_87;
     Goldilocks::copy(tmp_87, params.pols[7 + i*15]);
     Goldilocks::Element tmp_88;
     Goldilocks::copy(tmp_88, params.pols[9 + i*15]);
     Goldilocks3::Element tmp_48;
     Goldilocks3::mul(tmp_48, tmp_86, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_49;
     Goldilocks3::add(tmp_49, tmp_87, tmp_48);
     Goldilocks3::Element tmp_50;
     Goldilocks3::sub(tmp_50, tmp_49, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_51;
     Goldilocks3::mul(tmp_51, tmp_88, tmp_50);
     Goldilocks3::Element tmp_89;
     Goldilocks3::add(tmp_89, tmp_51, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[49158 + i*12]), tmp_89, (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks::Element tmp_90;
     Goldilocks::copy(tmp_90, params.pols[8 + i*15]);
     Goldilocks::Element tmp_91;
     Goldilocks::copy(tmp_91, params.pols[8 + i*15]);
     Goldilocks::Element tmp_92;
     Goldilocks::copy(tmp_92, params.pols[10 + i*15]);
     Goldilocks3::Element tmp_52;
     Goldilocks3::mul(tmp_52, tmp_90, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_53;
     Goldilocks3::add(tmp_53, tmp_91, tmp_52);
     Goldilocks3::Element tmp_54;
     Goldilocks3::sub(tmp_54, tmp_53, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_55;
     Goldilocks3::mul(tmp_55, tmp_92, tmp_54);
     Goldilocks3::Element tmp_93;
     Goldilocks3::add(tmp_93, tmp_55, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[49161 + i*12]), tmp_93, (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks::Element tmp_94;
     Goldilocks::copy(tmp_94, params.pols[2 + i*15]);
     Goldilocks3::Element tmp_56;
     Goldilocks3::mul(tmp_56, (Goldilocks::Element &)*params.x_n[i], (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_57;
     Goldilocks3::add(tmp_57, tmp_94, tmp_56);
     Goldilocks3::Element tmp_95;
     Goldilocks3::add(tmp_95, tmp_57, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks::Element tmp_96;
     Goldilocks::copy(tmp_96, params.pols[3 + i*15]);
     Goldilocks3::Element tmp_58;
     Goldilocks3::mul(tmp_58, Goldilocks::fromU64(12275445934081160404ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_59;
     Goldilocks3::mul(tmp_59, (Goldilocks::Element &)*params.x_n[i], tmp_58);
     Goldilocks3::Element tmp_60;
     Goldilocks3::add(tmp_60, tmp_96, tmp_59);
     Goldilocks3::Element tmp_61;
     Goldilocks3::add(tmp_61, tmp_60, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_97;
     Goldilocks3::mul(tmp_97, tmp_95, tmp_61);
     Goldilocks::Element tmp_98;
     Goldilocks::copy(tmp_98, params.pols[4 + i*15]);
     Goldilocks3::Element tmp_62;
     Goldilocks3::mul(tmp_62, Goldilocks::fromU64(4756475762779100925ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_63;
     Goldilocks3::mul(tmp_63, (Goldilocks::Element &)*params.x_n[i], tmp_62);
     Goldilocks3::Element tmp_64;
     Goldilocks3::add(tmp_64, tmp_98, tmp_63);
     Goldilocks3::Element tmp_65;
     Goldilocks3::add(tmp_65, tmp_64, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[21519 + i*21]), tmp_97, tmp_65);
     Goldilocks::Element tmp_99;
     Goldilocks::copy(tmp_99,  params.pConstPols->getElement(3,i));
     Goldilocks3::Element tmp_66;
     Goldilocks3::mul(tmp_66, tmp_99, (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_67;
     Goldilocks3::add(tmp_67, tmp_94, tmp_66);
     Goldilocks3::Element tmp_100;
     Goldilocks3::add(tmp_100, tmp_67, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks::Element tmp_101;
     Goldilocks::copy(tmp_101,  params.pConstPols->getElement(4,i));
     Goldilocks3::Element tmp_68;
     Goldilocks3::mul(tmp_68, tmp_101, (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_69;
     Goldilocks3::add(tmp_69, tmp_96, tmp_68);
     Goldilocks3::Element tmp_70;
     Goldilocks3::add(tmp_70, tmp_69, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_102;
     Goldilocks3::mul(tmp_102, tmp_100, tmp_70);
     Goldilocks::Element tmp_103;
     Goldilocks::copy(tmp_103,  params.pConstPols->getElement(5,i));
     Goldilocks3::Element tmp_71;
     Goldilocks3::mul(tmp_71, tmp_103, (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_72;
     Goldilocks3::add(tmp_72, tmp_98, tmp_71);
     Goldilocks3::Element tmp_73;
     Goldilocks3::add(tmp_73, tmp_72, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[21522 + i*21]), tmp_102, tmp_73);
}

void AllSteps::step3prev_last(StepsParams &params, uint64_t i) {
     Goldilocks::Element tmp_74;
     Goldilocks::copy(tmp_74, params.pols[12 + i*15]);
     Goldilocks::Element tmp_75;
     Goldilocks::copy(tmp_75, params.pols[13 + ((i + 1)%1024)*15]);
     Goldilocks::Element tmp_76;
     Goldilocks::mul(tmp_76, params.pols[12 + i*15], params.pols[13 + ((i + 1)%1024)*15]);
     Goldilocks::Element tmp_77;
     Goldilocks::copy(tmp_77,  params.pConstPols->getElement(7,i));
     Goldilocks::Element tmp_78;
     Goldilocks::copy(tmp_78,  params.pConstPols->getElement(8,i));
     Goldilocks::Element tmp_79;
     Goldilocks::copy(tmp_79, params.pols[14 + i*15]);
     Goldilocks::Element tmp_80;
     Goldilocks::copy(tmp_80,  params.pConstPols->getElement(6,i));
     Goldilocks3::Element tmp_12;
     Goldilocks3::mul(tmp_12, tmp_77, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_13;
     Goldilocks3::add(tmp_13, tmp_78, tmp_12);
     Goldilocks3::Element tmp_14;
     Goldilocks3::mul(tmp_14, (Goldilocks3::Element &)*params.challenges[0], tmp_13);
     Goldilocks3::Element tmp_15;
     Goldilocks3::add(tmp_15, tmp_79, tmp_14);
     Goldilocks3::Element tmp_16;
     Goldilocks3::sub(tmp_16, tmp_15, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_17;
     Goldilocks3::mul(tmp_17, tmp_80, tmp_16);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[49152 + i*12]), tmp_17, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks::Element tmp_81;
     Goldilocks::copy(tmp_81, params.pols[11 + i*15]);
     Goldilocks3::Element tmp_18;
     Goldilocks3::mul(tmp_18, tmp_74, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_19;
     Goldilocks3::add(tmp_19, tmp_75, tmp_18);
     Goldilocks3::Element tmp_20;
     Goldilocks3::mul(tmp_20, tmp_19, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_21;
     Goldilocks3::add(tmp_21, tmp_76, tmp_20);
     Goldilocks3::Element tmp_22;
     Goldilocks3::sub(tmp_22, tmp_21, (Goldilocks3::Element &)(params.pols[49152 + i*12]));
     Goldilocks3::Element tmp_23;
     Goldilocks3::mul(tmp_23, tmp_81, tmp_22);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[21513 + i*21]), tmp_23, (Goldilocks3::Element &)(params.pols[49152 + i*12]));
     Goldilocks::Element tmp_82;
     Goldilocks::copy(tmp_82,  params.pConstPols->getElement(7,(i+1)%1024));
     Goldilocks::Element tmp_83;
     Goldilocks::copy(tmp_83,  params.pConstPols->getElement(8,(i+1)%1024));
     Goldilocks::Element tmp_84;
     Goldilocks::copy(tmp_84, params.pols[14 + ((i + 1)%1024)*15]);
     Goldilocks::Element tmp_85;
     Goldilocks::copy(tmp_85,  params.pConstPols->getElement(6,(i+1)%1024));
     Goldilocks3::Element tmp_24;
     Goldilocks3::mul(tmp_24, tmp_82, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_25;
     Goldilocks3::add(tmp_25, tmp_83, tmp_24);
     Goldilocks3::Element tmp_26;
     Goldilocks3::mul(tmp_26, (Goldilocks3::Element &)*params.challenges[0], tmp_25);
     Goldilocks3::Element tmp_27;
     Goldilocks3::add(tmp_27, tmp_84, tmp_26);
     Goldilocks3::Element tmp_28;
     Goldilocks3::sub(tmp_28, tmp_27, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_29;
     Goldilocks3::mul(tmp_29, tmp_85, tmp_28);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[49152 + ((i + 1)%1024)*12]), tmp_29, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_30;
     Goldilocks3::add(tmp_30, (Goldilocks3::Element &)(params.pols[21513 + i*21]), (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_31;
     Goldilocks3::mul(tmp_31, (Goldilocks3::Element &)(params.pols[49152 + ((i + 1)%1024)*12]), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_32;
     Goldilocks3::add(tmp_32, (Goldilocks3::Element &)(params.pols[49152 + i*12]), tmp_31);
     Goldilocks3::Element tmp_33;
     Goldilocks3::add(tmp_33, Goldilocks::fromU64(1ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_34;
     Goldilocks3::mul(tmp_34, (Goldilocks3::Element &)*params.challenges[2], tmp_33);
     Goldilocks3::Element tmp_35;
     Goldilocks3::add(tmp_35, tmp_32, tmp_34);
     Goldilocks3::Element tmp_36;
     Goldilocks3::mul(tmp_36, tmp_30, tmp_35);
     Goldilocks3::Element tmp_37;
     Goldilocks3::add(tmp_37, Goldilocks::fromU64(1ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[21516 + i*21]), tmp_36, tmp_37);
     Goldilocks3::Element tmp_38;
     Goldilocks3::mul(tmp_38, (Goldilocks3::Element &)(params.pols[15363 + i*6]), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_39;
     Goldilocks3::add(tmp_39, (Goldilocks3::Element &)(params.pols[15360 + i*6]), tmp_38);
     Goldilocks3::Element tmp_40;
     Goldilocks3::add(tmp_40, Goldilocks::fromU64(1ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_41;
     Goldilocks3::mul(tmp_41, (Goldilocks3::Element &)*params.challenges[2], tmp_40);
     Goldilocks3::Element tmp_42;
     Goldilocks3::add(tmp_42, tmp_39, tmp_41);
     Goldilocks3::Element tmp_43;
     Goldilocks3::mul(tmp_43, (Goldilocks3::Element &)(params.pols[15360 + ((i + 1)%1024)*6]), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_44;
     Goldilocks3::add(tmp_44, (Goldilocks3::Element &)(params.pols[15363 + i*6]), tmp_43);
     Goldilocks3::Element tmp_45;
     Goldilocks3::add(tmp_45, Goldilocks::fromU64(1ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_46;
     Goldilocks3::mul(tmp_46, (Goldilocks3::Element &)*params.challenges[2], tmp_45);
     Goldilocks3::Element tmp_47;
     Goldilocks3::add(tmp_47, tmp_44, tmp_46);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[49155 + i*12]), tmp_42, tmp_47);
     Goldilocks::Element tmp_86;
     Goldilocks::copy(tmp_86, params.pols[7 + i*15]);
     Goldilocks::Element tmp_87;
     Goldilocks::copy(tmp_87, params.pols[7 + i*15]);
     Goldilocks::Element tmp_88;
     Goldilocks::copy(tmp_88, params.pols[9 + i*15]);
     Goldilocks3::Element tmp_48;
     Goldilocks3::mul(tmp_48, tmp_86, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_49;
     Goldilocks3::add(tmp_49, tmp_87, tmp_48);
     Goldilocks3::Element tmp_50;
     Goldilocks3::sub(tmp_50, tmp_49, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_51;
     Goldilocks3::mul(tmp_51, tmp_88, tmp_50);
     Goldilocks3::Element tmp_89;
     Goldilocks3::add(tmp_89, tmp_51, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[49158 + i*12]), tmp_89, (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks::Element tmp_90;
     Goldilocks::copy(tmp_90, params.pols[8 + i*15]);
     Goldilocks::Element tmp_91;
     Goldilocks::copy(tmp_91, params.pols[8 + i*15]);
     Goldilocks::Element tmp_92;
     Goldilocks::copy(tmp_92, params.pols[10 + i*15]);
     Goldilocks3::Element tmp_52;
     Goldilocks3::mul(tmp_52, tmp_90, (Goldilocks3::Element &)*params.challenges[0]);
     Goldilocks3::Element tmp_53;
     Goldilocks3::add(tmp_53, tmp_91, tmp_52);
     Goldilocks3::Element tmp_54;
     Goldilocks3::sub(tmp_54, tmp_53, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::Element tmp_55;
     Goldilocks3::mul(tmp_55, tmp_92, tmp_54);
     Goldilocks3::Element tmp_93;
     Goldilocks3::add(tmp_93, tmp_55, (Goldilocks3::Element &)*params.challenges[1]);
     Goldilocks3::add((Goldilocks3::Element &)(params.pols[49161 + i*12]), tmp_93, (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks::Element tmp_94;
     Goldilocks::copy(tmp_94, params.pols[2 + i*15]);
     Goldilocks3::Element tmp_56;
     Goldilocks3::mul(tmp_56, (Goldilocks::Element &)*params.x_n[i], (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_57;
     Goldilocks3::add(tmp_57, tmp_94, tmp_56);
     Goldilocks3::Element tmp_95;
     Goldilocks3::add(tmp_95, tmp_57, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks::Element tmp_96;
     Goldilocks::copy(tmp_96, params.pols[3 + i*15]);
     Goldilocks3::Element tmp_58;
     Goldilocks3::mul(tmp_58, Goldilocks::fromU64(12275445934081160404ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_59;
     Goldilocks3::mul(tmp_59, (Goldilocks::Element &)*params.x_n[i], tmp_58);
     Goldilocks3::Element tmp_60;
     Goldilocks3::add(tmp_60, tmp_96, tmp_59);
     Goldilocks3::Element tmp_61;
     Goldilocks3::add(tmp_61, tmp_60, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_97;
     Goldilocks3::mul(tmp_97, tmp_95, tmp_61);
     Goldilocks::Element tmp_98;
     Goldilocks::copy(tmp_98, params.pols[4 + i*15]);
     Goldilocks3::Element tmp_62;
     Goldilocks3::mul(tmp_62, Goldilocks::fromU64(4756475762779100925ULL), (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_63;
     Goldilocks3::mul(tmp_63, (Goldilocks::Element &)*params.x_n[i], tmp_62);
     Goldilocks3::Element tmp_64;
     Goldilocks3::add(tmp_64, tmp_98, tmp_63);
     Goldilocks3::Element tmp_65;
     Goldilocks3::add(tmp_65, tmp_64, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[21519 + i*21]), tmp_97, tmp_65);
     Goldilocks::Element tmp_99;
     Goldilocks::copy(tmp_99,  params.pConstPols->getElement(3,i));
     Goldilocks3::Element tmp_66;
     Goldilocks3::mul(tmp_66, tmp_99, (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_67;
     Goldilocks3::add(tmp_67, tmp_94, tmp_66);
     Goldilocks3::Element tmp_100;
     Goldilocks3::add(tmp_100, tmp_67, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks::Element tmp_101;
     Goldilocks::copy(tmp_101,  params.pConstPols->getElement(4,i));
     Goldilocks3::Element tmp_68;
     Goldilocks3::mul(tmp_68, tmp_101, (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_69;
     Goldilocks3::add(tmp_69, tmp_96, tmp_68);
     Goldilocks3::Element tmp_70;
     Goldilocks3::add(tmp_70, tmp_69, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::Element tmp_102;
     Goldilocks3::mul(tmp_102, tmp_100, tmp_70);
     Goldilocks::Element tmp_103;
     Goldilocks::copy(tmp_103,  params.pConstPols->getElement(5,i));
     Goldilocks3::Element tmp_71;
     Goldilocks3::mul(tmp_71, tmp_103, (Goldilocks3::Element &)*params.challenges[3]);
     Goldilocks3::Element tmp_72;
     Goldilocks3::add(tmp_72, tmp_98, tmp_71);
     Goldilocks3::Element tmp_73;
     Goldilocks3::add(tmp_73, tmp_72, (Goldilocks3::Element &)*params.challenges[2]);
     Goldilocks3::mul((Goldilocks3::Element &)(params.pols[21522 + i*21]), tmp_102, tmp_73);
}
