#include "goldilocks_cubic_extension.hpp"
#include "zhInv.hpp"
#include "starks.hpp"
#include "constant_pols_starks.hpp"
#include "fibonacciSteps.hpp"

void FibonacciSteps::step52ns_first(StepsParams &params, uint64_t i) {
     Goldilocks3::Element tmp_25;
     Goldilocks3::mul(tmp_25, params.pols[6144 + i*2], (Goldilocks3::Element &)*params.challenges[5]);
     Goldilocks3::Element tmp_26;
     Goldilocks3::add(tmp_26, params.pols[6145 + i*2], tmp_25);
     Goldilocks3::Element tmp_27;
     Goldilocks3::mul(tmp_27, (Goldilocks3::Element &)*params.challenges[5], tmp_26);
     Goldilocks3::Element tmp_28;
     Goldilocks3::add(tmp_28, params.pols[10240 + i*1], tmp_27);
     Goldilocks3::Element tmp_29;
     Goldilocks3::mul(tmp_29, (Goldilocks3::Element &)*params.challenges[5], tmp_28);
     Goldilocks3::Element tmp_30;
     Goldilocks3::add(tmp_30, tmp_29, (Goldilocks3::Element &)(params.pols[12288 + i*3]));
     Goldilocks3::Element tmp_31;
     Goldilocks3::mul(tmp_31, (Goldilocks3::Element &)*params.challenges[5], tmp_30);
     Goldilocks3::Element tmp_32;
     Goldilocks3::sub(tmp_32, params.pols[6144 + i*2], (Goldilocks3::Element &)*params.evals[1]);
     Goldilocks3::Element tmp_33;
     Goldilocks3::mul(tmp_33, tmp_32, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_34;
     Goldilocks3::sub(tmp_34, params.pConstPols2ns->getElement(1,i), (Goldilocks3::Element &)*params.evals[2]);
     Goldilocks3::Element tmp_35;
     Goldilocks3::add(tmp_35, tmp_33, tmp_34);
     Goldilocks3::Element tmp_36;
     Goldilocks3::mul(tmp_36, tmp_35, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_37;
     Goldilocks3::sub(tmp_37, params.pols[10240 + i*1], (Goldilocks3::Element &)*params.evals[4]);
     Goldilocks3::Element tmp_38;
     Goldilocks3::add(tmp_38, tmp_36, tmp_37);
     Goldilocks3::Element tmp_39;
     Goldilocks3::mul(tmp_39, tmp_38, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_40;
     Goldilocks3::sub(tmp_40, params.pols[6145 + i*2], (Goldilocks3::Element &)*params.evals[5]);
     Goldilocks3::Element tmp_41;
     Goldilocks3::add(tmp_41, tmp_39, tmp_40);
     Goldilocks3::Element tmp_42;
     Goldilocks3::mul(tmp_42, tmp_41, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_43;
     Goldilocks3::sub(tmp_43, params.pConstPols2ns->getElement(0,i), (Goldilocks3::Element &)*params.evals[6]);
     Goldilocks3::Element tmp_44;
     Goldilocks3::add(tmp_44, tmp_42, tmp_43);
     Goldilocks3::Element tmp_45;
     Goldilocks3::mul(tmp_45, tmp_44, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_46;
     Goldilocks3::sub(tmp_46, (Goldilocks3::Element &)(params.pols[12288 + i*3]), (Goldilocks3::Element &)*params.evals[7]);
     Goldilocks3::Element tmp_47;
     Goldilocks3::add(tmp_47, tmp_45, tmp_46);
     Goldilocks3::Element tmp_48;
     Goldilocks3::mul(tmp_48, (Goldilocks3::Element &)*params.xDivXSubXi[i], tmp_47);
     Goldilocks3::Element tmp_49;
     Goldilocks3::add(tmp_49, tmp_31, tmp_48);
     Goldilocks3::Element tmp_50;
     Goldilocks3::mul(tmp_50, (Goldilocks3::Element &)*params.challenges[5], tmp_49);
     Goldilocks3::Element tmp_51;
     Goldilocks3::sub(tmp_51, params.pols[6145 + i*2], (Goldilocks3::Element &)*params.evals[0]);
     Goldilocks3::Element tmp_52;
     Goldilocks3::mul(tmp_52, tmp_51, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_53;
     Goldilocks3::sub(tmp_53, params.pols[6144 + i*2], (Goldilocks3::Element &)*params.evals[3]);
     Goldilocks3::Element tmp_54;
     Goldilocks3::add(tmp_54, tmp_52, tmp_53);
     Goldilocks3::Element tmp_55;
     Goldilocks3::mul(tmp_55, (Goldilocks3::Element &)*params.xDivXSubWXi[i], tmp_54);
     Goldilocks3::Element tmp_56;
     Goldilocks3::add(tmp_56, tmp_50, tmp_55);
     Goldilocks3::copy((Goldilocks3::Element &)(params.f_2ns[i * 3]), tmp_56);
}

void FibonacciSteps::step52ns_i(StepsParams &params, uint64_t i) {
     Goldilocks3::Element tmp_25;
     Goldilocks3::mul(tmp_25, params.pols[6144 + i*2], (Goldilocks3::Element &)*params.challenges[5]);
     Goldilocks3::Element tmp_26;
     Goldilocks3::add(tmp_26, params.pols[6145 + i*2], tmp_25);
     Goldilocks3::Element tmp_27;
     Goldilocks3::mul(tmp_27, (Goldilocks3::Element &)*params.challenges[5], tmp_26);
     Goldilocks3::Element tmp_28;
     Goldilocks3::add(tmp_28, params.pols[10240 + i*1], tmp_27);
     Goldilocks3::Element tmp_29;
     Goldilocks3::mul(tmp_29, (Goldilocks3::Element &)*params.challenges[5], tmp_28);
     Goldilocks3::Element tmp_30;
     Goldilocks3::add(tmp_30, tmp_29, (Goldilocks3::Element &)(params.pols[12288 + i*3]));
     Goldilocks3::Element tmp_31;
     Goldilocks3::mul(tmp_31, (Goldilocks3::Element &)*params.challenges[5], tmp_30);
     Goldilocks3::Element tmp_32;
     Goldilocks3::sub(tmp_32, params.pols[6144 + i*2], (Goldilocks3::Element &)*params.evals[1]);
     Goldilocks3::Element tmp_33;
     Goldilocks3::mul(tmp_33, tmp_32, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_34;
     Goldilocks3::sub(tmp_34, params.pConstPols2ns->getElement(1,i), (Goldilocks3::Element &)*params.evals[2]);
     Goldilocks3::Element tmp_35;
     Goldilocks3::add(tmp_35, tmp_33, tmp_34);
     Goldilocks3::Element tmp_36;
     Goldilocks3::mul(tmp_36, tmp_35, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_37;
     Goldilocks3::sub(tmp_37, params.pols[10240 + i*1], (Goldilocks3::Element &)*params.evals[4]);
     Goldilocks3::Element tmp_38;
     Goldilocks3::add(tmp_38, tmp_36, tmp_37);
     Goldilocks3::Element tmp_39;
     Goldilocks3::mul(tmp_39, tmp_38, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_40;
     Goldilocks3::sub(tmp_40, params.pols[6145 + i*2], (Goldilocks3::Element &)*params.evals[5]);
     Goldilocks3::Element tmp_41;
     Goldilocks3::add(tmp_41, tmp_39, tmp_40);
     Goldilocks3::Element tmp_42;
     Goldilocks3::mul(tmp_42, tmp_41, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_43;
     Goldilocks3::sub(tmp_43, params.pConstPols2ns->getElement(0,i), (Goldilocks3::Element &)*params.evals[6]);
     Goldilocks3::Element tmp_44;
     Goldilocks3::add(tmp_44, tmp_42, tmp_43);
     Goldilocks3::Element tmp_45;
     Goldilocks3::mul(tmp_45, tmp_44, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_46;
     Goldilocks3::sub(tmp_46, (Goldilocks3::Element &)(params.pols[12288 + i*3]), (Goldilocks3::Element &)*params.evals[7]);
     Goldilocks3::Element tmp_47;
     Goldilocks3::add(tmp_47, tmp_45, tmp_46);
     Goldilocks3::Element tmp_48;
     Goldilocks3::mul(tmp_48, (Goldilocks3::Element &)*params.xDivXSubXi[i], tmp_47);
     Goldilocks3::Element tmp_49;
     Goldilocks3::add(tmp_49, tmp_31, tmp_48);
     Goldilocks3::Element tmp_50;
     Goldilocks3::mul(tmp_50, (Goldilocks3::Element &)*params.challenges[5], tmp_49);
     Goldilocks3::Element tmp_51;
     Goldilocks3::sub(tmp_51, params.pols[6145 + i*2], (Goldilocks3::Element &)*params.evals[0]);
     Goldilocks3::Element tmp_52;
     Goldilocks3::mul(tmp_52, tmp_51, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_53;
     Goldilocks3::sub(tmp_53, params.pols[6144 + i*2], (Goldilocks3::Element &)*params.evals[3]);
     Goldilocks3::Element tmp_54;
     Goldilocks3::add(tmp_54, tmp_52, tmp_53);
     Goldilocks3::Element tmp_55;
     Goldilocks3::mul(tmp_55, (Goldilocks3::Element &)*params.xDivXSubWXi[i], tmp_54);
     Goldilocks3::Element tmp_56;
     Goldilocks3::add(tmp_56, tmp_50, tmp_55);
     Goldilocks3::copy((Goldilocks3::Element &)(params.f_2ns[i * 3]), tmp_56);
}

void FibonacciSteps::step52ns_last(StepsParams &params, uint64_t i) {
     Goldilocks3::Element tmp_25;
     Goldilocks3::mul(tmp_25, params.pols[6144 + i*2], (Goldilocks3::Element &)*params.challenges[5]);
     Goldilocks3::Element tmp_26;
     Goldilocks3::add(tmp_26, params.pols[6145 + i*2], tmp_25);
     Goldilocks3::Element tmp_27;
     Goldilocks3::mul(tmp_27, (Goldilocks3::Element &)*params.challenges[5], tmp_26);
     Goldilocks3::Element tmp_28;
     Goldilocks3::add(tmp_28, params.pols[10240 + i*1], tmp_27);
     Goldilocks3::Element tmp_29;
     Goldilocks3::mul(tmp_29, (Goldilocks3::Element &)*params.challenges[5], tmp_28);
     Goldilocks3::Element tmp_30;
     Goldilocks3::add(tmp_30, tmp_29, (Goldilocks3::Element &)(params.pols[12288 + i*3]));
     Goldilocks3::Element tmp_31;
     Goldilocks3::mul(tmp_31, (Goldilocks3::Element &)*params.challenges[5], tmp_30);
     Goldilocks3::Element tmp_32;
     Goldilocks3::sub(tmp_32, params.pols[6144 + i*2], (Goldilocks3::Element &)*params.evals[1]);
     Goldilocks3::Element tmp_33;
     Goldilocks3::mul(tmp_33, tmp_32, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_34;
     Goldilocks3::sub(tmp_34, params.pConstPols2ns->getElement(1,i), (Goldilocks3::Element &)*params.evals[2]);
     Goldilocks3::Element tmp_35;
     Goldilocks3::add(tmp_35, tmp_33, tmp_34);
     Goldilocks3::Element tmp_36;
     Goldilocks3::mul(tmp_36, tmp_35, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_37;
     Goldilocks3::sub(tmp_37, params.pols[10240 + i*1], (Goldilocks3::Element &)*params.evals[4]);
     Goldilocks3::Element tmp_38;
     Goldilocks3::add(tmp_38, tmp_36, tmp_37);
     Goldilocks3::Element tmp_39;
     Goldilocks3::mul(tmp_39, tmp_38, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_40;
     Goldilocks3::sub(tmp_40, params.pols[6145 + i*2], (Goldilocks3::Element &)*params.evals[5]);
     Goldilocks3::Element tmp_41;
     Goldilocks3::add(tmp_41, tmp_39, tmp_40);
     Goldilocks3::Element tmp_42;
     Goldilocks3::mul(tmp_42, tmp_41, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_43;
     Goldilocks3::sub(tmp_43, params.pConstPols2ns->getElement(0,i), (Goldilocks3::Element &)*params.evals[6]);
     Goldilocks3::Element tmp_44;
     Goldilocks3::add(tmp_44, tmp_42, tmp_43);
     Goldilocks3::Element tmp_45;
     Goldilocks3::mul(tmp_45, tmp_44, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_46;
     Goldilocks3::sub(tmp_46, (Goldilocks3::Element &)(params.pols[12288 + i*3]), (Goldilocks3::Element &)*params.evals[7]);
     Goldilocks3::Element tmp_47;
     Goldilocks3::add(tmp_47, tmp_45, tmp_46);
     Goldilocks3::Element tmp_48;
     Goldilocks3::mul(tmp_48, (Goldilocks3::Element &)*params.xDivXSubXi[i], tmp_47);
     Goldilocks3::Element tmp_49;
     Goldilocks3::add(tmp_49, tmp_31, tmp_48);
     Goldilocks3::Element tmp_50;
     Goldilocks3::mul(tmp_50, (Goldilocks3::Element &)*params.challenges[5], tmp_49);
     Goldilocks3::Element tmp_51;
     Goldilocks3::sub(tmp_51, params.pols[6145 + i*2], (Goldilocks3::Element &)*params.evals[0]);
     Goldilocks3::Element tmp_52;
     Goldilocks3::mul(tmp_52, tmp_51, (Goldilocks3::Element &)*params.challenges[6]);
     Goldilocks3::Element tmp_53;
     Goldilocks3::sub(tmp_53, params.pols[6144 + i*2], (Goldilocks3::Element &)*params.evals[3]);
     Goldilocks3::Element tmp_54;
     Goldilocks3::add(tmp_54, tmp_52, tmp_53);
     Goldilocks3::Element tmp_55;
     Goldilocks3::mul(tmp_55, (Goldilocks3::Element &)*params.xDivXSubWXi[i], tmp_54);
     Goldilocks3::Element tmp_56;
     Goldilocks3::add(tmp_56, tmp_50, tmp_55);
     Goldilocks3::copy((Goldilocks3::Element &)(params.f_2ns[i * 3]), tmp_56);
}
