#ifndef POSEIDON_G_PERMUTATION_HPP
#define POSEIDON_G_PERMUTATION_HPP

#define POSEIDONG_PERMUTATION1_ID 1
#define POSEIDONG_PERMUTATION2_ID 2
#define POSEIDONG_PERMUTATION3_ID 3
#define POSEIDONG_PERMUTATION4_ID 4

#endif