#ifndef BINARY_DEFINES_HPP
#define BINARY_DEFINES_HPP

#define REGISTERS_NUM 8
#define BYTES_PER_REGISTER 4
#define STEPS_PER_REGISTER 2
#define STEPS (STEPS_PER_REGISTER * REGISTERS_NUM)
#define LATCH_SIZE ( REGISTERS_NUM * STEPS_PER_REGISTER )

#endif